# Generated by Django 4.1.2 on 2022-11-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='supervisor',
            new_name='owner',
        ),
    ]
