# Generated by Django 4.1.2 on 2022-12-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_rename_supervisor_course_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supervisor',
            new_name='MyUser',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='instructor',
        ),
    ]
