# Generated by Django 4.1.2 on 2022-12-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_myuser_address_myuser_email_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='permission',
            field=models.CharField(choices=[('TA', 'TA'), ('Professor', 'Professor'), ('Supervisor', 'Supervisor')], default='TA', max_length=20),
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('starttime', models.CharField(max_length=20)),
                ('endtime', models.CharField(max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_app.myuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_app.course')),
            ],
        ),
    ]
