# Generated by Django 4.1.2 on 2022-12-13 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_rename_name_myuser_user_name_remove_course_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='project_app.myuser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='permission',
            field=models.CharField(choices=[('TA', 'TA'), ('Instructor', 'Instructor'), ('Supervisor', 'Supervisor')], default='TA', max_length=20),
        ),
    ]
