# Generated by Django 4.1.2 on 2022-12-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_alter_course_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='permission',
            field=models.CharField(choices=[('TA', 'TA'), ('Instructor', 'Instructor'), ('Supervisor', 'Supervisor')], default='Supervisor', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='endtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='starttime',
            field=models.DateField(),
        ),
    ]
