# Generated by Django 4.1.2 on 2022-12-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_myuser_permission_alter_section_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='endtime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='starttime',
            field=models.CharField(max_length=10),
        ),
    ]
